### ISSUE TITLE
Travis OSX failing on async arrow functions in Javascript

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-mpfd#14]
This issue is raised in metanorma-mpfd, but relates to Javascript invoked in metanorma: bin/metanorma-pdf.js

I'm on OSX, and the Javascript in Metanorma generating PDF has not raised an issue to date:

`const createPdf = async() => {`

(taken from https://www.forsbergplustwo.com/blogs/news/pdf-generation-with-chrome-headless-in-ruby-using-puppeteer-on-heroku)

This is not failing on Travis Linux either, but is failing on Travis OSX:

````
/Users/travis/build/metanorma/metanorma-mpfd/vendor/bundle/ruby/2.5.0/gems/metanorma-0.3.11/bin/metanorma-pdf.js:6
const createPdf = async() => {
                       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
````

Since this is legal Javascript, I consider this to be a Travis issue (OSX not getting provided with Javascript ES6 somehow), and I'm raising it as an issue.

**Comment by CAMOBAP795** [comment]
Fixed in https://github.com/metanorma/metanorma-mpfd/pull/15
